apiVersion: apps/v1
kind: Deployment
metadata: 
  name: node-app-deployment
  labels:
    app: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: localhost:5000/my-node-app:latest
        ports:
        - containerPort: 3010
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu:  "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"