apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: nodejs-app-listener
spec:
  serviceAccountName: tekton-trigger-sa
  triggers:
    - name: nodejs-app-trigger
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["push"]
      bindings:
        - ref: pipeline-binding
      template:
        ref: pipeline-template