apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: nodejs-app-pipeline
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: git-url
      type: string
      default: https://github.com/hassam-01/sample_devops1.git
    - name: git-revision
      type: string
      default: main
    - name: image
      type: string
      default: docker.io/hassamali404/sample_devops1:latest
  tasks:
    - name: fetch-source
      taskRef:
        name: fetch-source
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: install-dependencies
      taskRef:
        name: npm-install
      runAfter:
        - fetch-source
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: run-unit-tests
      taskRef:
        name: test
      runAfter:
        - install-dependencies
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: build-docker-image
      taskRef:
        name: build-image  # Fixed: was "build", should be "build-image"
      params:
        - name: image
          value: $(params.image)
      runAfter:
        - run-unit-tests  # Fixed: was "run-unit-test"
      workspaces:
        - name: source
          workspace: shared-workspace